### ISSUE TITLE
Disable QR code display

### ISSUE THREAD

**Issue by rfuehrer** [generaliinformatik/scrumonline#14]
...the temptation is just too big ;) The display of the QR code must be disabled to prevent the usage from internal. networks more comprehensible. Scanning the QR with a private device for when the destination address is not reached, this leads to an error. Therefore the distribution of the link or the session ID is to be preferred.

**Comment by ageof** [comment]
Feature has been implemented: [disable_qr_code](https://github.com/generaliinformatik/scrumonline/tree/feature/disable_qr_code)

**Comment by ageof2** [comment]
Feature has been implemented: [disable_qr_code](https://github.com/generaliinformatik/scrumonline/tree/feature/disable_qr_code)
